In [1]:
import numpy as np

In [2]:
np.arange(4)

array([0, 1, 2, 3])

In [3]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [4]:
np.arange(2,8,2)

array([2, 4, 6])

In [5]:
np.linspace(2,7,10)

array([2.        , 2.55555556, 3.11111111, 3.66666667, 4.22222222,
       4.77777778, 5.33333333, 5.88888889, 6.44444444, 7.        ])

In [6]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])